# Expense Service
# Categories
GET http://localhost:5196/api/Categories/GetAllCategories

###
GET http://localhost:5196/api/Categories/GetCategoryById/d402952a-ac6d-42ba-ab42-70c238f23016


### Auth Service

# Get Users with JWT Token
Get http://localhost:5197/api/Users/GetUsers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtYmFya3RpZXN0b0BvdXRsb29rLmNvbSIsImp0aSI6ImE1MTBhODMyLWZhODEtNDcyMy1hZDJhLWZjOGJkMjFhNDcwNCIsImV4cCI6MTcwMzYyMDY3NiwiaXNzIjoiRXhwZW5vdmFBcHAiLCJhdWQiOiJFeHBlbm92YUFwcCJ9.UDsSyIgLTwV5xTvsbV3wLWbNmw82iKxVMezdMLvWHVQ





# Gateway Service

# Expenses Service

### Categories

GET http://localhost:5274/ExpenseService/Api/Categories/GetAllCategories

###
GET http://localhost:5274/ExpenseService/Api/Categories/GetCategoryById/d402952a-ac6d-42ba-ab42-70c238f23016

###
POST http://localhost:5274/ExpenseService/Api/Categories/CreateCategory
Content-Type: application/json

{
  "name": "",
  "description": "",
  "userId": "26d371d8-fd39-4f99-a564-daacae87344e"
}


###
GET http://localhost:5274/AuthService/Api/Users/GetUsers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtYmFya3RpZXN0b0BvdXRsb29rLmNvbSIsImp0aSI6IjkwMGIzYjk0LTk0NmYtNGJlZS05YTZlLWZiODA3ODQ5MTRjMCIsImV4cCI6MTcwMzY2NTAwMSwiaXNzIjoiRXhwZW5vdmFBcHAiLCJhdWQiOiJFeHBlbm92YUFwcCJ9.CaMUouzzVGA1Laxkh6NX_9iMjaeOIb_IOuUHeBqXJHU



### Subscription Expense
POST http://localhost:5196/api/SubscriptionExpense/Create
Content-Type: application/json

{
  "amount": 666,
  "description": "666",
  "startDate": "2024-02-14T10:48:25.990Z",
  "endDate": "2024-06-14T10:48:25.990Z",
  "recurrenceInterval": 3,
  "billingAmount": 666,
  "userId": "e044a393-fcde-41ea-8331-b32be623a7e0",
  "categoryId": "2024da3a-8e3f-42b7-8cc5-62e92b372cf1"
}